version: '3.1'

services:

  redmine:
    image: redmine
    ports:
      - 13000:3000
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_PASSWORD: example
    links:
      - db:postgres
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - /mnt/sda1/docker/redmine/public/postgres:/var/lib/postgresql/data
    restart: always
